name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Raylib Dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get -y install sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
    - name: Install Raylib
      run: |
        git clone https://github.com/raysan5/raylib.git raylib
        cd raylib
        mkdir build && cd build
        cmake -DBUILD_SHARED_LIBS=ON -DUSE_WAYLAND=ON
        make 
        sudo make install
    - name: Build Project
      run: |
        make

    - name: Run Tests
      run: |
        make check

    - name: Distribution Check
      run: |
        make distcheck
